baseURL: "https://fabian.damken.net/"
title: Fabian Damken
theme: PaperMod

copyright: "[Impressum](/impressum/) | [Datenschutzerklärung](/privacy/) &nbsp;---"

enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false
enableGitInfo: true
custom_css: css/style.css

minify:
  disableXML: false
  minifyOutput: true

outputs:
  home:
    - HTML
    - JSON

params:
  title: Fabian Damken
  description: "My personal web page."
  keywords: []
  author: Fabian Damken
  images: []
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableFingerprinting: true
    favicon: favicon.png
    favicon16x16: favicon16x16.png
    favicon32x32: favicon32x32.png
    apple_touch_icon: apple_touch_icon.png
    safari_pinned_tab: safari_pinned_tab.png

  profileMode:
    enabled: true
    title: Fabian Damken
    imageUrl: me.jpg
    imageWidth: 500
    imageHeight: " "
    imageTitle: me
    buttons:
      - name: "Go to My Summaries"
        url: summaries

  socialIcons:
#    - name: cv
#      url: /static/resume.pdf
    - name: linkedin
      url: "https://linkedin.com/in/fdamken"
    - name: googlescholar
      url: "https://scholar.google.com/citations?user=EM-y6hYAAAAJ"
    - name: github
      url: "https://github.com/fdamken"
    - name: twitter
      url: "https://twitter.com/fabian_damken"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/4907452"
    - name: email
      url: "mailto:fabian@damken.net?subject=Contact via fabian.damken.net&body=Hi%20Fabian%2C%0A%0A%E2%80%A6"

menu:
  main:
#    - identifier: resume
#      name: Résumé
#      url: /static/resume.pdf
#      weight: 10
    - identifier: latex
      name: LaTeX
      url: /latex
      weight: 20
    - identifier: proof-of-work
      name: Proof of Work
      url: /proof-of-work
      weight: 30
    - identifier: summaries
      name: Summaries
      url: /summaries
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
